### ISSUE TITLE
Inline svg inside bemjson snippet not escaped properly.

### ISSUE THREAD

**Issue by Guria** [bem-archive/bem-site-engine#125]
Inline svg in usage example of `icon` block not escaped on site and rendered as image.
See last example of bemjson on [`icon` block documentation page](https://ru.bem.info/libs/bem-components/v2.0.0/desktop/icon/)

**Comment by tadatuta** [comment]
cc @tavriaforever @gela-d

**Comment by gela-d** [comment]
funny bug :) Thank u, we'll fix

**Comment by Guria** [comment]
@gela-d I had to see this page a lot of times before I got that this is actually a bug.
