### ISSUE TITLE
Search doesn't work on the //ru.bem.info

### ISSUE THREAD

**Issue by Baskins** [bem-archive/bem-site-engine#176]
I'm not sure about this repo, but i can't find but report button on the //ru.bem.info
So, let me inform you about bug in this issue.
Search doesn't work. There some problem whit Ajax and server side
U can see this screenshot http://take.ms/51ty5

**Comment by Baskins** [comment]
Mac OS and latest Safari ver 8.0.6 (10600.6.3)

**Comment by tadatuta** [comment]
@Baskins thank you!

**Comment by tavriaforever** [comment]
Hi! Code to fix bug already in [production](https://ru.bem.info/). 
Thanks.
